apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blockchain-js-ui
  labels:
    run: blockchain-js-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      run: blockchain-js-ui
  strategy:
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: blockchain-js-ui
    spec:
      containers:
      - name: blockchain-js-ui
        image: eu.gcr.io/blockchain-js/blockchain-js-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 443
          protocol: TCP
      - name: http-redirect
        image: eu.gcr.io/blockchain-js/http-redirect:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
      - name: blockchain-js-core
        image: eu.gcr.io/blockchain-js/blockchain-js-core:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9091
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-js-ui
  labels:
    run: blockchain-js-ui
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 35.187.182.86
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: signal
    protocol: TCP
    port: 8999
    targetPort: 8999
  - name: http-redirect
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: node-core
    protocol: TCP
    port: 9091
    targetPort: 9091
  selector:
    run: blockchain-js-ui